import { LauncherItem } from "./types";
import {
  Football,
  Basketball,
  Baseball,
  Circle,
  SoccerBall,
  GraduationCap,
  FlagPennant,
  Article,
  ChartBar,
  User,
  Calendar,
  ListNumbers,
  Newspaper,
  GlobeHemisphereWest,
} from "@phosphor-icons/react";

export const manifest: LauncherItem[] = [
  // NFL
  {
    id: "nfl",
    name: "NFL",
    description: "National Football League",
    icon: Football,
    category: "NFL",
    tags: ["football", "nfl"],
    prefixes: ["nfl:", "n:"],
    keywords: ["football", "national football league"],
    children: [
      {
        id: "nfl-panthers",
        name: "Carolina Panthers",
        description: "NFC South",
        icon: Football,
        category: "NFL",
        tags: ["carolina", "panthers", "nfc-south"],
        keywords: ["carolina panthers"],
        children: [
          {
            id: "nfl-panthers-schedule",
            name: "Schedule",
            description: "2025-26 season schedule",
            icon: Calendar,
            category: "NFL",
            tags: ["schedule", "games"],
            keywords: [],
          },
          {
            id: "nfl-panthers-roster",
            name: "Roster",
            description: "Current roster and depth chart",
            icon: User,
            category: "NFL",
            tags: ["roster", "players"],
            keywords: [],
          },
          {
            id: "nfl-panthers-stats",
            name: "Stats",
            description: "Team and player statistics",
            icon: ChartBar,
            category: "NFL",
            tags: ["stats", "statistics"],
            keywords: [],
          },
          {
            id: "nfl-panthers-news",
            name: "News",
            description: "Latest team news",
            icon: Newspaper,
            category: "NFL",
            tags: ["news", "updates"],
            keywords: [],
          },
          {
            id: "nfl-panthers-standings",
            name: "Standings",
            description: "NFC South standings",
            icon: ListNumbers,
            category: "NFL",
            tags: ["standings", "rankings"],
            keywords: [],
          },
        ],
      },
      {
        id: "nfl-chiefs",
        name: "Kansas City Chiefs",
        description: "AFC West",
        icon: Football,
        category: "NFL",
        tags: ["kansas-city", "chiefs", "afc-west"],
        keywords: ["kansas city chiefs"],
        children: [
          {
            id: "nfl-chiefs-schedule",
            name: "Schedule",
            icon: Calendar,
            category: "NFL",
            tags: ["schedule"],
            keywords: [],
          },
          {
            id: "nfl-chiefs-roster",
            name: "Roster",
            icon: User,
            category: "NFL",
            tags: ["roster"],
            keywords: [],
          },
          {
            id: "nfl-chiefs-stats",
            name: "Stats",
            icon: ChartBar,
            category: "NFL",
            tags: ["stats"],
            keywords: [],
          },
        ],
      },
      {
        id: "nfl-bills",
        name: "Buffalo Bills",
        description: "AFC East",
        icon: Football,
        category: "NFL",
        tags: ["buffalo", "bills", "afc-east"],
        keywords: ["buffalo bills"],
        children: [
          {
            id: "nfl-bills-schedule",
            name: "Schedule",
            icon: Calendar,
            category: "NFL",
            tags: ["schedule"],
            keywords: [],
          },
          {
            id: "nfl-bills-roster",
            name: "Roster",
            icon: User,
            category: "NFL",
            tags: ["roster"],
            keywords: [],
          },
        ],
      },
    ],
  },
  // NBA
  {
    id: "nba",
    name: "NBA",
    description: "National Basketball Association",
    icon: Basketball,
    category: "NBA",
    tags: ["basketball", "nba"],
    prefixes: ["nba:", "b:"],
    keywords: ["basketball", "national basketball association"],
    children: [
      {
        id: "nba-lakers",
        name: "Los Angeles Lakers",
        description: "Pacific Division",
        icon: Basketball,
        category: "NBA",
        tags: ["lakers", "los-angeles", "pacific"],
        keywords: ["los angeles lakers"],
        children: [
          {
            id: "nba-lakers-schedule",
            name: "Schedule",
            icon: Calendar,
            category: "NBA",
            tags: ["schedule"],
            keywords: [],
          },
          {
            id: "nba-lakers-roster",
            name: "Roster",
            icon: User,
            category: "NBA",
            tags: ["roster"],
            keywords: [],
          },
          {
            id: "nba-lakers-stats",
            name: "Stats",
            icon: ChartBar,
            category: "NBA",
            tags: ["stats"],
            keywords: [],
          },
        ],
      },
      {
        id: "nba-blazers",
        name: "Portland Trail Blazers",
        description: "Northwest Division",
        icon: Basketball,
        category: "NBA",
        tags: ["blazers", "portland", "northwest"],
        keywords: ["portland trail blazers"],
        children: [
          {
            id: "nba-blazers-schedule",
            name: "Schedule",
            icon: Calendar,
            category: "NBA",
            tags: ["schedule"],
            keywords: [],
          },
          {
            id: "nba-blazers-roster",
            name: "Roster",
            icon: User,
            category: "NBA",
            tags: ["roster"],
            keywords: [],
          },
        ],
      },
    ],
  },
  // MLB
  {
    id: "mlb",
    name: "MLB",
    description: "Major League Baseball",
    icon: Baseball,
    category: "MLB",
    tags: ["baseball", "mlb"],
    prefixes: ["mlb:", "m:"],
    keywords: ["baseball", "major league baseball"],
    children: [
      {
        id: "mlb-tigers",
        name: "LSU Tigers",
        description: "College Baseball",
        icon: Baseball,
        category: "MLB",
        tags: ["lsu", "tigers", "college"],
        keywords: ["lsu tigers baseball"],
        children: [
          {
            id: "mlb-tigers-schedule",
            name: "Schedule",
            icon: Calendar,
            category: "MLB",
            tags: ["schedule"],
            keywords: [],
          },
          {
            id: "mlb-tigers-roster",
            name: "Roster",
            icon: User,
            category: "MLB",
            tags: ["roster"],
            keywords: [],
          },
        ],
      },
    ],
  },
  // College
  {
    id: "college",
    name: "College Sports",
    description: "NCAA athletics",
    icon: GraduationCap,
    category: "College",
    tags: ["college", "ncaa", "university"],
    prefixes: ["college:", "c:"],
    keywords: ["college", "ncaa", "university"],
    children: [
      {
        id: "college-michigan",
        name: "Michigan Wolverines",
        description: "Big Ten Conference",
        icon: GraduationCap,
        category: "College",
        tags: ["michigan", "wolverines", "big-ten"],
        keywords: ["michigan wolverines"],
        children: [
          {
            id: "college-michigan-football",
            name: "Football",
            icon: Football,
            category: "College",
            tags: ["football"],
            keywords: [],
            children: [
              {
                id: "college-michigan-football-schedule",
                name: "Schedule",
                icon: Calendar,
                category: "College",
                tags: ["schedule"],
                keywords: [],
              },
              {
                id: "college-michigan-football-roster",
                name: "Roster",
                icon: User,
                category: "College",
                tags: ["roster"],
                keywords: [],
              },
              {
                id: "college-michigan-football-stats",
                name: "Stats",
                icon: ChartBar,
                category: "College",
                tags: ["stats"],
                keywords: [],
              },
            ],
          },
          {
            id: "college-michigan-basketball",
            name: "Basketball",
            icon: Basketball,
            category: "College",
            tags: ["basketball"],
            keywords: [],
            children: [
              {
                id: "college-michigan-basketball-schedule",
                name: "Schedule",
                icon: Calendar,
                category: "College",
                tags: ["schedule"],
                keywords: [],
              },
              {
                id: "college-michigan-basketball-roster",
                name: "Roster",
                icon: User,
                category: "College",
                tags: ["roster"],
                keywords: [],
              },
            ],
          },
          {
            id: "college-michigan-hockey",
            name: "Hockey",
            icon: Circle,
            category: "College",
            tags: ["hockey"],
            keywords: [],
          },
          {
            id: "college-michigan-baseball",
            name: "Baseball",
            icon: Baseball,
            category: "College",
            tags: ["baseball"],
            keywords: [],
          },
        ],
      },
      {
        id: "college-unc",
        name: "North Carolina Tar Heels",
        description: "ACC",
        icon: GraduationCap,
        category: "College",
        tags: ["unc", "carolina", "tar-heels", "acc"],
        keywords: ["north carolina tar heels"],
        children: [
          {
            id: "college-unc-basketball",
            name: "Basketball",
            icon: Basketball,
            category: "College",
            tags: ["basketball"],
            keywords: [],
            children: [
              {
                id: "college-unc-basketball-schedule",
                name: "Schedule",
                icon: Calendar,
                category: "College",
                tags: ["schedule"],
                keywords: [],
              },
              {
                id: "college-unc-basketball-roster",
                name: "Roster",
                icon: User,
                category: "College",
                tags: ["roster"],
                keywords: [],
              },
              {
                id: "college-unc-basketball-stats",
                name: "Stats",
                icon: ChartBar,
                category: "College",
                tags: ["stats"],
                keywords: [],
              },
            ],
          },
        ],
      },
      {
        id: "college-lsu",
        name: "LSU Tigers",
        description: "SEC",
        icon: GraduationCap,
        category: "College",
        tags: ["lsu", "tigers", "sec"],
        keywords: ["lsu tigers"],
        children: [
          {
            id: "college-lsu-football",
            name: "Football",
            icon: Football,
            category: "College",
            tags: ["football"],
            keywords: [],
          },
          {
            id: "college-lsu-baseball",
            name: "Baseball",
            icon: Baseball,
            category: "College",
            tags: ["baseball"],
            keywords: [],
          },
        ],
      },
    ],
  },
  // Golf
  {
    id: "golf",
    name: "Golf (PGA Tour)",
    description: "Professional golf",
    icon: FlagPennant,
    category: "Golf",
    tags: ["golf", "pga"],
    prefixes: ["golf:", "g:"],
    keywords: ["golf", "pga tour"],
    children: [
      {
        id: "golf-bhatia",
        name: "Akshay Bhatia",
        description: "Professional Golfer",
        icon: User,
        category: "Golf",
        tags: ["akshay-bhatia", "player"],
        keywords: ["akshay bhatia"],
        children: [
          {
            id: "golf-bhatia-stats",
            name: "Stats",
            icon: ChartBar,
            category: "Golf",
            tags: ["stats"],
            keywords: [],
          },
          {
            id: "golf-bhatia-schedule",
            name: "Schedule",
            icon: Calendar,
            category: "Golf",
            tags: ["schedule"],
            keywords: [],
          },
        ],
      },
      {
        id: "golf-koepka",
        name: "Brooks Koepka",
        description: "Professional Golfer",
        icon: User,
        category: "Golf",
        tags: ["brooks-koepka", "player"],
        keywords: ["brooks koepka"],
        children: [
          {
            id: "golf-koepka-stats",
            name: "Stats",
            icon: ChartBar,
            category: "Golf",
            tags: ["stats"],
            keywords: [],
          },
        ],
      },
      {
        id: "golf-leaderboard",
        name: "Live Leaderboard",
        description: "Current tournament standings",
        icon: ListNumbers,
        category: "Golf",
        tags: ["leaderboard", "live"],
        keywords: [],
      },
    ],
  },
  // External
  {
    id: "espn",
    name: "ESPN",
    description: "Sports news and scores",
    icon: GlobeHemisphereWest,
    category: "External",
    tags: ["espn", "news", "external"],
    url: "https://espn.com",
    keywords: ["espn sports"],
  },
  {
    id: "the-athletic",
    name: "The Athletic",
    description: "Sports journalism",
    icon: Article,
    category: "External",
    tags: ["athletic", "news", "external"],
    url: "https://theathletic.com",
    keywords: ["the athletic"],
  },
  {
    id: "sports-reference",
    name: "Sports Reference",
    description: "Stats and historical data",
    icon: ChartBar,
    category: "External",
    tags: ["stats", "reference", "external"],
    url: "https://sports-reference.com",
    keywords: ["sports reference statistics"],
  },
];

// Flatten all items for search
export function getAllItems(items: LauncherItem[] = manifest): LauncherItem[] {
  const result: LauncherItem[] = [];
  
  function traverse(item: LauncherItem) {
    result.push(item);
    if (item.children) {
      item.children.forEach(traverse);
    }
  }
  
  items.forEach(traverse);
  return result;
}
